---
title: "Mangroves"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)
library(ggspatial)

```

```{r}
load(file.path(project_path, "data", "02_processed_data", "admin","common_spatial_inputs.RData"))
```

```{r, eval = F}
gmw <- read_sf(file.path(emlab_data_path, "global-mangrove-watch", "GMW_2016_v2.shp"))

mangroves_uac_pnch <- gmw %>% 
  st_make_valid() %>% 
  st_crop(st_buffer(uac_pnch, dist = 1))

write_sf(mangroves_uac_pnch, file.path(project_path, "data", "02_processed_data", "mangroves_uac_pnch.gpkg"))
```

```{r}
mangroves_uac_pnch <- read_sf(file.path(project_path, "data", "02_processed_data", "mangroves_uac_pnch.gpkg")) %>% 
  st_transform(crs = col_crs)

col_background_plot+
  geom_sf(data = st_crop(col_land, st_union(drmi_gtcc, utria)))+
  geom_sf(data = st_crop(mangroves_uac_pnch, st_union(drmi_gtcc, utria)), col = "transparent", fill = "darkgreen")+
  coord_sf(xlim = c(as.double(st_bbox(st_union(drmi_gtcc, utria))["xmin"]), as.double(st_bbox(st_union(drmi_gtcc, utria))["xmax"])+.1), 
           ylim = c(as.double(st_bbox(st_union(drmi_gtcc, utria))["ymin"]), as.double(st_bbox(st_union(drmi_gtcc, utria))["ymax"])), 
           expand = FALSE)+
  ggspatial::annotation_scale(location = "br", width_hint = 0.2, style = "ticks", 
                              pad_y = unit(0.05, units =  "native"), pad_x = unit(0.05, units =  "native") )+
  ggspatial::annotation_north_arrow(location = "tl", which_north = "true", height = unit(0.1, "native"), width = unit(0.1, "native"),
                                    pad_x = unit(0.05, "native"), pad_y = unit(0.05, "native"),
                                    style = north_arrow_fancy_orienteering)+
  labs(title = "Manglares - Golfo de Tribugá")+
  ggsave(filename = file.path(project_path, "figures", "mangroves_drmi_gtcc.png"), 
         dpi = 300)
```

